name: Run Selenium Tests with Chrome 129

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del c贸digo fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar dependencias de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 3: Instalar Chrome y ChromeDriver versi贸n 129 desde "Chrome for Testing"
      - name: Install Chrome 129 and ChromeDriver 129
        run: |
          # Descargar y extraer Chrome versi贸n 129
          wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/129.0.3945.88/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip -d chrome/
          sudo mv chrome/chrome-linux64/chrome /usr/local/bin/
          sudo chmod +x /usr/local/bin/chrome

          # Descargar y extraer ChromeDriver versi贸n 129
          wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/129.0.3945.88/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip -d chromedriver/
          sudo mv chromedriver/chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

          # Verificar las versiones instaladas
          /usr/local/bin/chrome --version
          /usr/local/bin/chromedriver --version

      # Paso 4: Ejecutar las pruebas con Selenium
      - name: Run tests
        run: |
          pytest  # O el comando que prefieras para ejecutar las pruebas






