name: Run Tests on Ubuntu with Chrome 129

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Checkout del c칩digo
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar dependencias
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Especifica la versi칩n de Python que est치s usando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      # Paso 3: Instalar Chrome y ChromeDriver
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -fy install
          google-chrome --version  # Verifica que se ha instalado la versi칩n correcta

      - name: Install ChromeDriver 129
        run: |
          wget -N https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/129.0.0.0/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip -d /usr/local/bin/
          sudo mv /usr/local/bin/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version  # Verifica que se ha instalado ChromeDriver 129

      # Paso 4: Correr las pruebas
      - name: Run tests
        run: |
          pytest  # O el comando que uses para ejecutar las pruebas




