name: Run Selenium Tests with Chrome 129

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del c贸digo fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar dependencias de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 3: Descargar e instalar Chrome y ChromeDriver versi贸n 129 desde "Chrome for Testing"
      - name: Install Chrome 129 and ChromeDriver 129
        run: |
          set -e  # Detener en caso de error

          echo "Descargando Chrome 129..."
          wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/129.0.3945.88/linux64/chrome-linux64.zip || { echo "Error al descargar Chrome"; exit 1; }
          
          echo "Extrayendo Chrome..."
          unzip chrome-linux64.zip -d chrome/ || { echo "Error al extraer Chrome"; exit 1; }
          
          sudo mv chrome/chrome-linux64/chrome /usr/local/bin/ || { echo "Error al mover Chrome"; exit 1; }
          sudo chmod +x /usr/local/bin/chrome || { echo "Error al cambiar permisos de Chrome"; exit 1; }

          echo "Descargando ChromeDriver 129..."
          wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/129.0.3945.88/linux64/chromedriver-linux64.zip || { echo "Error al descargar ChromeDriver"; exit 1; }

          echo "Extrayendo ChromeDriver..."
          unzip chromedriver-linux64.zip -d chromedriver/ || { echo "Error al extraer ChromeDriver"; exit 1; }

          sudo mv chromedriver/chromedriver-linux64/chromedriver /usr/local/bin/ || { echo "Error al mover ChromeDriver"; exit 1; }
          sudo chmod +x /usr/local/bin/chromedriver || { echo "Error al cambiar permisos de ChromeDriver"; exit 1; }

          echo "Verificando versiones instaladas..."
          /usr/local/bin/chrome --version || { echo "Error al verificar versi贸n de Chrome"; exit 1; }
          /usr/local/bin/chromedriver --version || { echo "Error al verificar versi贸n de ChromeDriver"; exit 1; }

      # Paso 4: Ejecutar las pruebas con Selenium
      - name: Run tests
        run: |
          pytest  # O el comando que prefieras para ejecutar las pruebas







