name: Proyecto Tienda Nube

on: 
  push:
  
  workflow_dispatch: #Permite ejecutar el flow manualmente

jobs:
  build:
    runs-on: ubuntu-latest  # Cambiado a Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Instalar Chrome en la instancia de Ubuntu
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
    
    # Instalar ChromeDriver
    - name: Install ChromeDriver
    run: |
      wget -N https://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
      unzip chromedriver_linux64.zip
      sudo mv chromedriver /usr/local/bin/
      sudo chmod +x /usr/local/bin/chromedriver
  

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pytest --html=report.html

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: report.html


